# Generated by Django 6.0.4 on 2026-04-23 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('BLOQUEADA', 'Bloqueada')], default='PENDENTE', max_length=10)),
                ('mensagem', models.CharField(blank=True, max_length=200)),
                ('dh_completo', models.BooleanField(default=False)),
                ('dh_parametros_remetente', models.TextField(blank=True, null=True)),
                ('dh_parametros_destinatario', models.TextField(blank=True, null=True)),
                ('segredo_compartilhado', models.BinaryField(blank=True, null=True)),
                ('canal_seguro', models.BooleanField(default=False)),
                ('algoritmo_canal', models.CharField(default='AES-256-GCM', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amizade',
                'verbose_name_plural': 'Amizades',
                'db_table': 'amizades',
                'ordering': ['-criado_em'],
                'unique_together': {('remetente', 'destinatario')},
            },
        ),
        migrations.CreateModel(
            name='ChaveCriptografica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algoritmo', models.CharField(choices=[('RSA-1024', 'RSA 1024'), ('RSA-2048', 'RSA 2048'), ('ElGamal-1024', 'ElGamal 1024'), ('DiffieHellman', 'Diffie-Hellman')], max_length=20)),
                ('tipo', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], max_length=10)),
                ('chave_data', models.TextField()),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('parametros_dh', models.TextField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('revogada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chaves_criptograficas',
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DIRETA', 'Direta'), ('GRUPO', 'Grupo')], default='DIRETA', max_length=10)),
                ('algoritmo_padrao', models.CharField(default='HIBRIDO-RSA', max_length=20)),
                ('hash_padrao', models.CharField(default='BLAKE3', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_mensagem', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True)),
                ('amizade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversa', to='api.amizade')),
                ('participantes', models.ManyToManyField(related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'db_table': 'conversas',
                'ordering': ['-ultima_mensagem'],
            },
        ),
        migrations.CreateModel(
            name='LogCriptografia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operacao', models.CharField(max_length=50)),
                ('algoritmo', models.CharField(max_length=50)),
                ('parametros', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs_criptografia',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('online', models.BooleanField(default=False)),
                ('ultimo_visto', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEM', 'Imagem'), ('AUDIO', 'Áudio'), ('VIDEO', 'Vídeo'), ('ARQUIVO', 'Arquivo')], default='TEXTO', max_length=10)),
                ('algoritmo', models.CharField(choices=[('RSA-1024', 'RSA 1024'), ('RSA-2048', 'RSA 2048'), ('ElGamal-1024', 'ElGamal 1024'), ('HIBRIDO', 'Híbrido (RSA+AES)'), ('ECC', 'Curvas Elípticas')], max_length=20)),
                ('conteudo_cifrado', models.BinaryField()),
                ('metadados_cifrados', models.BinaryField(blank=True, null=True)),
                ('hash_algoritmo', models.CharField(choices=[('SHA-256', 'SHA-256'), ('SHA3-512', 'SHA3-512'), ('BLAKE3', 'BLAKE3')], max_length=10)),
                ('hash_original', models.CharField(max_length=128)),
                ('hash_verificado', models.BooleanField(default=False)),
                ('assinatura', models.BinaryField(blank=True, null=True)),
                ('assinatura_verificada', models.BooleanField(default=False)),
                ('algoritmo_assinatura', models.CharField(default='RSA-PSS', max_length=20)),
                ('nonce', models.BinaryField()),
                ('ephemeral_key', models.BinaryField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='api.conversa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'mensagens',
                'ordering': ['enviada_em'],
                'indexes': [models.Index(fields=['conversa', 'enviada_em'], name='mensagens_convers_60b766_idx'), models.Index(fields=['remetente', 'enviada_em'], name='mensagens_remeten_81adff_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('AMIZADE', 'Solicitação de Amizade'), ('AMIZADE_ACEITA', 'Amizade Aceita'), ('MENSAGEM', 'Nova Mensagem'), ('SISTEMA', 'Sistema'), ('CHAMADA', 'Chamada')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('dados', models.TextField(default='{}')),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('entregue_websocket', models.BooleanField(default=False)),
                ('entregue_push', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacoes',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['usuario', 'lida'], name='notificacoe_usuario_56e4b8_idx'), models.Index(fields=['tipo'], name='notificacoe_tipo_c35bdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAmizade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('mensagem', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to='api.perfil')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to='api.perfil')),
            ],
            options={
                'verbose_name': 'Solicitação de Amizade',
                'verbose_name_plural': 'Solicitações de Amizade',
                'db_table': 'solicitacoes_amizade',
                'ordering': ['-criado_em'],
                'unique_together': {('remetente', 'destinatario')},
            },
        ),
    ]
