# Generated by Django 6.0.4 on 2026-04-23 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoridadeCertificadora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('certificado_pem', models.TextField()),
                ('chave_privada', models.TextField()),
                ('valido_de', models.DateTimeField()),
                ('valido_ate', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('nivel', models.IntegerField(default=1)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autoridade Certificadora',
                'verbose_name_plural': 'Autoridades Certificadoras',
                'db_table': 'autoridades_certificadoras',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servico', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_pem', models.TextField()),
                ('chave_publica_pem', models.TextField()),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('subject', models.TextField()),
                ('issuer', models.TextField()),
                ('valido_de', models.DateTimeField()),
                ('valido_ate', models.DateTimeField()),
                ('status', models.CharField(choices=[('VALIDO', 'Válido'), ('REVOGADO', 'Revogado'), ('EXPIRADO', 'Expirado'), ('SUSPENSO', 'Suspenso')], default='VALIDO', max_length=10)),
                ('data_revogacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_revogacao', models.TextField(blank=True, null=True)),
                ('fingerprint_sha256', models.CharField(max_length=64, unique=True)),
                ('fingerprint_sha1', models.CharField(max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados_emitidos', to='api.autoridadecertificadora')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado Digital',
                'verbose_name_plural': 'Certificados Digitais',
                'db_table': 'certificados_digitais',
                'indexes': [models.Index(fields=['serial_number'], name='certificado_serial__2b061f_idx'), models.Index(fields=['fingerprint_sha256'], name='certificado_fingerp_c80c36_idx'), models.Index(fields=['status'], name='certificado_status_1bcee6_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogSeguranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico'), ('SECURITY', 'Segurança')], max_length=10)),
                ('evento', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('dados', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Segurança',
                'verbose_name_plural': 'Logs de Segurança',
                'db_table': 'logs_seguranca',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['nivel', 'timestamp'], name='logs_segura_nivel_5cfa73_idx'), models.Index(fields=['evento'], name='logs_segura_evento_54b867_idx'), models.Index(fields=['usuario'], name='logs_segura_usuario_6c4281_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField()),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
