# Generated by Django 4.2.7 on 2026-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_push_notifi_user_id_a10111_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='texto_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='algoritmo',
            field=models.CharField(choices=[('RSA-1024', 'RSA 1024'), ('RSA-2048', 'RSA 2048'), ('ElGamal-1024', 'ElGamal 1024'), ('HIBRIDO', 'Híbrido (RSA+AES)'), ('ECC', 'Curvas Elípticas'), ('HYBRID-RSA-AES-256-CBC', 'Híbrido RSA+AES-256')], default='HYBRID-RSA-AES-256-CBC', max_length=50),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='hash_algoritmo',
            field=models.CharField(choices=[('SHA-256', 'SHA-256'), ('SHA3-512', 'SHA3-512'), ('BLAKE3', 'BLAKE3')], default='SHA-256', max_length=10),
        ),
    ]
